### ISSUE TITLE
ItemDetailView 각종 버그 수정

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#105]
📌 Issue
- ItemDetailView 부터 진행되는 Flow 에 대한 버그를 수정합니다

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
- [x] ItemDetailView 스크롤 안됨
- [x] ItemDetailView 에서 TopAlertView 위치 너무 위에 뜸
- [x] ItemDetailView 에서 제목 패딩 안맞음
- [x] Icon 이름 문제 해결한거 반영 안됨
