### ISSUE TITLE
OCR 과 직접추가에서 아이템 등록과정 버그 수정

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#107]
📌 Issue
- OCR 과 직접추가에서 아이템 등록, 빠져나오는 과정 중 버그들을 수정합니다

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
- [x] 오늘 이전의 날짜로 직접추가 하면 메인화면에서 0일로 뜸 -> 날짜 반영 X
- [x] 카메라로 찍은 후, 수정할때 날짜를 바꾸면 바꾼 날짜가 적용이 안됨
- [x] scrollview 에서 제스쳐 삭제
- [x] CameraView 에서 갤러리 열었다가 취소하면 다음에 들어왔을때 다시 열려있는 버그 수정
- [x] 음수로 값이 들어온 경우 수정을 해도 음수로 등록되는 문제
