### ISSUE TITLE
HistoryView 수정

### ISSUE THREAD

**Issue by mollangcow** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#125]
📌 Issue

- 데이터 영구 보존으로 인해 화면상 일정기간 후 데이터 삭제 메시지를 제거합니다.
- 일부 디자인 오류를 바로잡습니다.

## 📝 To-do
- [x] ScrollView header warning message delete
- [x] List section topTrailing date count message delete
- [x] TapBar title size fix
- [x] List divider delete
