### ISSUE TITLE
UpdateItemView 수정

### ISSUE THREAD

**Issue by ChangJin-Lee** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#126]
📌 Issue
- UpdateItemView에서 품목 추가하기 눌렀을 때 모달로 띄워서 보여주기
- 직접 추가 완료했을 때 화면 영수증처럼 바꾸기
- 품목 추가하기 버튼과 다음 버튼 두개를 분리해서 만들기

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|영수증 화면처럼 바꾸기|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/859902fa-99cd-4795-9041-f3970abd7998">
|직접 추가 뷰 변경|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/d0cf863d-c696-4f2e-b53a-6b06f0c36487">
|직접 추가 뷰 변경|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/8098a435-d6e7-44e2-a36d-501e5d641c90">
|품목 추가 변경|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/ceabe389-08cd-436b-a53e-1cf22946bf86">

## 📝 To-do
- [x] UpdateItemView에서 품목 추가하기 눌렀을 때 모달로 띄워서 보여주기
- [x] 직접 추가 완료했을 때 화면 영수증처럼 바꾸기
- [x] 품목 추가하기 버튼과 다음 버튼 두개를 분리해서 만들기
