### ISSUE TITLE
CloudKit & CoreData 연동

### ISSUE THREAD

**Issue by ChangJin-Lee** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#132]
📌 Issue

- CloudKit과 CoreData 연동해야 해요

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
- [ ] CloudKit과 CoreData 연동
- [x] PersistentController 와 NSPersistentCloudKitContainer 연결
- [x] NSFetchRequest 로 get 구현
- [ ] CoreData의 결과를 CloudKit에 넘기기 위해 @FetchRequest 연결하기
