### ISSUE TITLE
mainView 구현

### ISSUE THREAD

**Issue by ChangJin-Lee** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#14]
📌 Issue

- mainView 를 구현하고 기능을 완성해요
- mainView에서 쓰일 BasicList를 구현해요
- mainView에서 쓰일 LongTermList를 구현해요
- mainView에서 쓰일 TabBarView를 구현해요

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|mainView|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/ce8f1cca-be37-4eec-a0d3-36dad64f674c">
|MainView + BasicList|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/e5b881f0-ee2d-4481-bf00-0bb0d73b4968">
|MainView + LongTermList|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/83225f46-3db7-4034-9c8c-3998b939537a">
||<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/aa01bd20-fc9c-423f-a749-008abe92fd18">

## 📝 To-do
- [x] mainView를 구현하고 기능 완성
- [x] mainView에서 쓰일 BasicList 구현
- [x]  mainView에서 쓰일 LongTermList 구현
- [x]  mainView에서 쓰일 TabBarView 구현

**Comment by ChangJin-Lee** [comment]
# 변경사항

1. BasicList와 LongTermList 둘 다 드래그 했을때 navigationTitle이 같이 움직여야하기 때문에 custom으로 Title 영역을 만들기로 함. 
<p align="center">
<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/478acf42-86a7-48e8-9cd2-60cae897a5f1" width = 40%>
   </p>

1. TabBarView에 navigationStack을 만들어서 depth를 들어가기로 함. 
    - 왜냐… settingView에서 TabBarView를 유지한 상태로 뎁스를 더 들어가야 함.
