### ISSUE TITLE
CoreData CRUD 연결

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#28]
📌 Issue
- 기존에 설계한 CoreData 모델 refactoring 및 ViewModel 에서 추가적인 기능 구현

## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [x] dateOfHistory attribute 만들기
- [x] MainView 에서 불러올때 가나다순으로 불러오기
- [x] 각종 sorting computed property 만들기
- [x] date difference extension 만들기
