### ISSUE TITLE
UpdateItemView 텍스트 입력 기능 

### ISSUE THREAD

**Issue by wonniiii** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#42]
📌 Issue
- UpdateItemView의 텍스트 관련 모든 기능 추가

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|텍스트 입력 관련 기능|<img width="618" alt="스크린샷 2023-07-24 오전 3 53 12" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/81157265/19e47ef9-744a-4ecd-abad-108803b08f4f">
|경고, x버튼|<img width="977" alt="스크린샷 2023-07-24 오전 3 53 34" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/81157265/51852584-615a-4c80-b362-85056f8106e4">
|alert 경고|<img width="1429" alt="스크린샷 2023-07-24 오전 3 54 01" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/81157265/336750e3-2b2c-4e9d-8af4-6ad2193ed5c8">

## 📝 To-do
- [x]  텍스트를 눌렀을 때 키보드가 올라오고 수정하기
- [x]  품목과 금액 입력 받기.
- ~~[ ]  금액에 숫자 입력시 자동으로 ‘원’ , ','이 생기게끔 만들기~~
- [x]  입력을 마무리하지 않고 완료 누를 경우 ItemBlockView 맨 아래에 경고 문구 띄우기
- [x]  항목을 삭제했을 때 해당하는 경고 문구를 포함하는 TopAlertView 띄우기.

**Comment by ChangJin-Lee** [comment]
해결완료...!
