### ISSUE TITLE
CoreData 연결하기

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#63]
📌 Issue
- 각 view 의 core data 가 필요한 부분에 연결하는 작업입니다

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|BasicListView|<img width="90" alt="스크린샷 2023-07-26 오전 1 04 31" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/0479fa30-ac9e-43a0-a65a-37a6d4b82120">
|LongTermListView|<img width="92" alt="스크린샷 2023-07-26 오전 1 04 42" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/0e9211e6-3569-4d24-a5ea-8d7982ee9bf8">
|HistoryView|<img width="118" alt="스크린샷 2023-07-26 오전 1 04 08" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/f88f51eb-0682-4796-8ce8-dec4d7fa246e">
|ItemCheckView|<img width="165" alt="스크린샷 2023-07-26 오전 1 03 14" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/d7ca2a78-52ea-4ae3-bfa4-5e6b4ea95f1a">
|ItemDetailView|<img width="114" alt="스크린샷 2023-07-26 오전 1 03 46" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/64433431-e0dc-441f-abfc-39121fbe4902">
|EditItemDetailView|<img width="175" alt="스크린샷 2023-07-26 오전 1 02 19" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/650229b9-74f2-4137-9715-80c3f1600bf7">

## 📝 To-do
- [x] BasicListView 에 CoreData 및 기능 연결
- [x] LongTermListView 에 CoreData 및 기능 연결
- [x] HistoryView 에 CoreData 및 기능 연결
