### ISSUE TITLE
ChatGPT OpenAI CameraView에 연결하기

### ISSUE THREAD

**Issue by ChangJin-Lee** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#64]
📌 Issue

- GPT API 연결하기
- OCR뷰에서 받은 1차원 Array를 GPT에게 request를 보낸 후 response를 받기.
- 받은 response를 itemCheckView로 값을 넘기기

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|chatGPT API 연결|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/54494793/2fbd8b00-b314-4042-96d6-3830d2242177">

## 📝 To-do
- [ ] GPT API 연결하기
- [ ] OCR뷰에서 받은 1차원 Array를 GPT에게 request를 보낸 후 response를 받기.
- [ ] 받은 response를 itemCheckView로 값을 넘기기

**Comment by ChangJin-Lee** [comment]
해결 완료!
