### ISSUE TITLE
SettingView 기능 구현하기

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#67]
📌 Issue
- SettingView 기능을 구현해요

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|SettingView|<img src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/13d5af12-47b3-4369-80cb-995c66b1214f">

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [ ] settingView layout 구성
- [ ] 시스템 세팅으로 이동기능 구현
- [ ] 각종 toggle 버튼끼리의 연관 구현
