### ISSUE TITLE
ItemDetailView 리팩토링

### ISSUE THREAD

**Issue by alpaka99** [DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA#94]
📌 Issue 
- ItemDetailView 버그 수정 및 디테일 조정

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|ItemDetailView|<img width="129" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/b708945e-a9e4-4064-82fd-88250c885042">
|EditItemDetailView|<img width="127" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-BALANCEIAGA/assets/22471820/e842a8b1-213c-40a7-81af-6642de1d1778">

## 📝 To-do
- [x] ItemDetailView 삭제 버그 수정
- [x] 먹었어요-상했어요 버튼 눌렀을때 MainView 로 빠져나가기
- [x] ItemDetailView 네비게이션 바 hidden 하고 custom top bar 에 뒤로 기능 추가
- [x] ItemDetailView 레이아웃 조정
- [x] 기본 아이콘 에셋 변경
- [x] ItemDetailView 에서 냉장고 선택하면 TopAlertView 띄우기
- [x] ItemDetailView 에서 삭제 클릭 시 CenterAlertView 를 띄워서 한번 더 물어보기
- [x] ItemDetailView 와 HistoryView 에서 아이템 삭제시 CenterAlertView 띄워서 다시 한번 물어보기
